seq_length = 1024
input_dim = 128
predictions_keys = ["exists", "x", "y", "time", "type", "hitSound"]
predictions_dim = 6
predictions_normalize = [512, 384, 1024, 255, 15]  # See https://osu.ppy.sh/wiki/en/Client/Playfield
exists_key = "exists"
batch_size = 64
end_token_weight = 1
predictions_weights = [4, 4, 1, 1, 1]
l1_alpha = 1
json_file_path_key = "file_path"
json_attributes_key = "attributes"
training_labels_file = "../input/training-layers.json"
test_labels_file = "../input/test-layers.json"
trained_model_path = "../pretrained_models/trained_model.pth"
best_model_path = "../pretrained_models/best_model.pth"
hit_object_keys = ["x", "y", "time", "type", "hitSound", "objectParams", "hitSample"]
beatmaps_directory = "../input/beatmaps"  # Store beatmaps into this directory
splice_directory = "../input/splices"  # Splices generated from preprocessor stored in this directory
audio_directory = "../input/audio"  # Contains audio files used for music of beatmap generation
output_directory = "../output/"  # Directory containing generated beatmaps
