seq_length = 1024
input_dim = 128
cnn_output_dim = 256
predictions_dim = 6 # [exists, x, y, time, type, hitSound]
batch_size = 4000
label_weight = 25
json_file_path_key = "file_path"
json_attributes_key = "attributes"
training_labels_file = "../input/training-layers.json"
test_labels_file = "../input/test-layers.json"
trained_model_path = "../pretrained_models/trained_model.pth"
hit_object_keys = ["x", "y", "time", "type", "hitSound", "objectParams", "hitSample"]
beatmaps_directory = '../input/beatmaps' # Store beatmaps into this directory
splice_directory = '../input/splices' # Store beatmaps into this directory
